"""Publish which checks this suite proves can fire, and which it does not.

WHY THE NUMBER HAD TO BE MEASURED RATHER THAN ESTIMATED

Counting how many check ids fire against the two shipped FIXTURES gave 398 of
790, and that figure was wrong in a way worth naming: `SODCOV-004` through
`SODCOV-010` never appear in a fixture run, while 57 unit tests drive them
directly. Fixture firing is not the same question as "does the suite prove this
check works", and answering the easy question instead of the asked one is the
defect this product reports on elsewhere.

So `tests/conftest.py` wraps `BaseAuditor.finding` for the whole session and
records every check id that fires ANYWHERE, and this tool turns that recording
into `docs/CHECK_FIRING.md`.

WHAT A CHECK IN THE UNPROVEN LIST MEANS, AND WHAT IT DOES NOT

It does NOT mean the check is broken. Most are pattern matchers that correctly
stay silent because no test supplies input matching them. What it means is that
nothing in this repository demonstrates the check can produce a finding at all -
so if it were dead, as five SoD rules were found to be, no test would say so.

Run after a FULL suite:

    python -m pytest tests/ -q
    python -m tools.build_firing_reference
"""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from modules import coverage                                   # noqa: E402

RECORDING = ROOT / "reports" / "check_firing.json"
OUTPUT = ROOT / "docs" / "CHECK_FIRING.md"

#: Families whose members are proven elsewhere by construction rather than by
#: firing. Listed with the reason, because a family excluded without one is
#: indistinguishable from a family quietly dropped.
PROVEN_BY_CONSTRUCTION = {
    "ARA": "every rule is proven satisfiable by tests/test_ara_batch2.py, which "
           "synthesises a grant from the rule's own predicates and asserts the "
           "conflict fires",
}


def load_recording() -> dict:
    if not RECORDING.exists():
        raise SystemExit(
            "no recording at %s. Run the full suite first:\n"
            "    python -m pytest tests/ -q" % RECORDING)
    return json.loads(RECORDING.read_text(encoding="utf-8"))


def build() -> str:
    rec = load_recording()
    fired = set(rec["fired"])
    catalogue = sorted(coverage.check_catalogue())
    known = set(catalogue)

    proven = sorted(known & fired)
    by_construction = sorted(
        c for c in known - fired
        if c.rsplit("-", 1)[0].split("-")[0] in PROVEN_BY_CONSTRUCTION)
    unproven = sorted(known - fired - set(by_construction))

    fam = collections.Counter(c.rsplit("-", 1)[0] for c in unproven)
    rows = "\n".join(
        "| `%s` | %d | %d |" % (f, n, sum(1 for c in catalogue
                                          if c.rsplit("-", 1)[0] == f))
        for f, n in fam.most_common(25))

    return """# Which checks are proven to fire

<!-- GENERATED FILE — DO NOT EDIT BY HAND.
     Produced by tools/build_firing_reference.py from a full test run. -->

**%d of %d** literal check ids are proven to produce a finding somewhere in the
test suite. A further **%d** are proven by construction. **%d** are unproven.

## What "unproven" means here

It does **not** mean the check is broken. Most unproven checks are pattern
matchers that correctly stay silent because no test supplies input matching
them. It means nothing in this repository demonstrates the check can produce a
finding at all — so if one were dead, as five segregation-of-duties rules were
found to be, no test would say so.

The figure is measured, not estimated. `tests/conftest.py` records every check
id that fires anywhere in the suite. Counting fixture runs alone gave a worse
answer: `SODCOV-004`..`SODCOV-010` never fire against a fixture while 57 unit
tests drive them directly.

## Proven by construction

%s

## Unproven, by family

| Family | Unproven | In catalogue |
|---|---:|---:|
%s

_Generated by `tools/build_firing_reference.py` after `python -m pytest tests/ -q`._
""" % (len(proven), len(catalogue), len(by_construction), len(unproven),
       "\n".join("- **`%s-*`** — %s" % (k, v)
                 for k, v in sorted(PROVEN_BY_CONSTRUCTION.items())),
       rows)


def main() -> int:
    OUTPUT.write_text(build(), encoding="utf-8")
    rec = load_recording()
    known = set(coverage.check_catalogue())
    fired = set(rec["fired"]) & known
    print("wrote %s — %d of %d proven to fire"
          % (OUTPUT.relative_to(ROOT), len(fired), len(known)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
